// GENRES
const GET_GENRES = "GET_GENRES";
const GET_GENRE_BY_ID = "GET_GENRE_BY_ID";
const UPDATE_GENRE = "UPDATE_GENRE";
const DELETE_GENRE = "DELETE_GENRE";
const CREATE_GENRE = "CREATE_GENRE";

//MOVIES
const GET_MOVIES = "GET_MOVIES";
const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
const UPDATE_MOVIE = "UPDATE_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const CREATE_MOVIE = "CREATE_MOVIE";

//CINEMA
const GET_CINEMAS = "GET_CINEMAS";
const GET_CINEMA_BY_ID = "GET_CINEMA_BY_ID";
const UPDATE_CINEMA = "UPDATE_CINEMA";
const DELETE_CINEMA = "DELETE_CINEMA";
const CREATE_CINEMA = "CREATE_CINEMA";

export default {
  GET_GENRES, GET_GENRE_BY_ID, UPDATE_GENRE, DELETE_GENRE, CREATE_GENRE,
  GET_MOVIES, GET_MOVIE_BY_ID, UPDATE_MOVIE, DELETE_MOVIE, CREATE_MOVIE,
  GET_CINEMAS, GET_CINEMA_BY_ID, UPDATE_CINEMA, DELETE_CINEMA, CREATE_CINEMA
} as any;