// GENRES
const GET_GENRES = "GET_GENRES";
const GET_GENRE_BY_ID = "GET_GENRE_BY_ID";
const UPDATE_GENRE = "UPDATE_GENRE";
const DELETE_GENRE = "DELETE_GENRE";
const CREATE_GENRE = "CREATE_GENRE";

//MOVIES
const GET_MOVIES = "GET_MOVIES";
const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
const UPDATE_MOVIE = "UPDATE_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const CREATE_MOVIE = "CREATE_MOVIE";

//CINEMA
const GET_CINEMAS = "GET_CINEMAS";
const GET_CINEMA_BY_ID = "GET_CINEMA_BY_ID";
const UPDATE_CINEMA = "UPDATE_CINEMA";
const DELETE_CINEMA = "DELETE_CINEMA";
const CREATE_CINEMA = "CREATE_CINEMA";

//ROOM
const GET_ROOMS = "GET_ROOMS";
const GET_ROOM_BY_ID = "GET_ROOM_BY_ID";
const UPDATE_ROOM = "UPDATE_ROOM";
const DELETE_ROOM = "DELETE_ROOM";
const CREATE_ROOM = "CREATE_ROOM";

//SCHEDULE
const GET_SCHEDULES = "GET_SCHEDULES";
const GET_SCHEDULE_BY_ID = "GET_SCHEDULE_BY_ID";
const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
const DELETE_SCHEDULE = "DELETE_SCHEDULE";
const CREATE_SCHEDULE = "CREATE_SCHEDULE";


//USER
const GET_USERS = "GET_USERS";
const GET_USER_BY_ID = "GET_USER_BY_ID";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";
const CREATE_USER = "CREATE_USER";

//CARD
const GET_CARD = "GET_CARD";

export default {
  GET_GENRES, GET_GENRE_BY_ID, UPDATE_GENRE, DELETE_GENRE, CREATE_GENRE,
  GET_MOVIES, GET_MOVIE_BY_ID, UPDATE_MOVIE, DELETE_MOVIE, CREATE_MOVIE,
  GET_CINEMAS, GET_CINEMA_BY_ID, UPDATE_CINEMA, DELETE_CINEMA, CREATE_CINEMA,
  GET_ROOMS, GET_ROOM_BY_ID, UPDATE_ROOM, DELETE_ROOM, CREATE_ROOM,
  GET_SCHEDULES, GET_SCHEDULE_BY_ID, UPDATE_SCHEDULE, DELETE_SCHEDULE, CREATE_SCHEDULE,
  GET_USERS, GET_USER_BY_ID, UPDATE_USER, DELETE_USER, CREATE_USER,
  GET_CARD
} as any;